### ISSUE TITLE
Not working after upgrading to Ubuntu 19.04 / Gnome 3.32

### ISSUE THREAD

**Issue by belenos** [shumingch/gnome-email-notifications#22]
Extension is not working on Ubuntu 19.04. It worked fine on 18.10 with Gnome 3.30.

**Comment by pandvan** [comment]
I can confirm.
Starting from the upgrade to Gnome 3.32 this extension stopped to work and the following error is showed on the journal.

```
[Gnome Email Notifications] this._construct is not a function,newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
   _createNotificationWithSource@/home/_user_/.local/share/gnome-shell/extensions/GmailMessageTray@shuming0207.gmail.com/NotificationFactory.js:128:30
   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
   _createNotification@/home/_user_/.local/share/gnome-shell/extensions/GmailMessageTray@shuming0207.gmail.com/NotificationFactory.js:113:16
   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
   createEmailNotification@/home/_user_/.local/share/gnome-shell/extensions/GmailMessageTray@shuming0207.gmail.com/NotificationFactory.js:60:9
   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
   displayUnreadMessages@/home/_user_/.local/share/gnome-shell/extensions/GmailMessageTray@shuming0207.gmail.com/Notifier.js:66:17
   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
   updateContent@/home/_user_/.local/share/gnome-shell/extensions/GmailMessageTray@shuming0207.gmail.com/EmailAccount.js:92:13
   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
   _processData@/home/_user_/.local/share/gnome-shell/extensions/GmailMessageTray@shuming0207.gmail.com/EmailAccount.js:79:17
   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
```
It seems related to this upstream issue https://gitlab.gnome.org/GNOME/gjs/issues/233 and other extensions had to do some refactor in order to get back working.
